#define HOVER_CONFIG_LOGFILE "/dev/stdout"

#define HOVER_CONFIG_PORT_STEERING 12
#define HOVER_CONFIG_PORT_HOVER 13
#define HOVER_CONFIG_PORT_FORWARD 11

#define HOVER_CONFIG_WEBSOCKET_ADDRESS "0.0.0.0"
#define HOVER_CONFIG_WEBSOCKET_PORT "1337"
